name: Generate Snake
on:
  schedule:
    - cron: '0 0 * * *'  # Раз в день
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: PDTPLR
          outputs: output/github-contribution-grid-snake-dark.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake
          path: output/github-contribution-grid-snake-dark.svg
      - name: Push snake to output branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b output || git checkout output
          git add output/github-contribution-grid-snake-dark.svg
          git commit -m "Update snake animation" || exit 0
          git push origin output --force
